import{i as f,a as F,S}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const x="49492514-812d245cc52e4f29e485c4df0",A="https://pixabay.com/api/",O={key:x,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15};function h(n){f.show({message:n,position:"topRight",timeout:7e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconUrl:"./img/icons/close.svg",closeOnEscape:!0,closeOnClick:!0,maxWidth:"432px"})}function p(n){f.show({message:n,position:"topRight",timeout:5e3,backgroundColor:"#59A10D",messageColor:"#FAFAFB",closeOnEscape:!0,closeOnClick:!0,maxWidth:"432px"})}async function v(n,t=1){const a=document.getElementById("loader");a.style.display="flex";try{return(await F.get(A,{params:{...O,q:n,page:t}})).data}catch(l){throw h("Failed to fetch images"),l}finally{a.style.display="none"}}let g=null;function E({totalHits:n,hits:t},a=!1){const l=document.getElementById("gallery");if(a||(l.innerHTML=""),t.length===0)return h("Sorry, there are no images matching your search query. Please try again!"),null;if(t.forEach(({webformatURL:e,largeImageURL:o,tags:s,likes:i,views:w,comments:B,downloads:I},b)=>{const L=[{title:"Likes",value:i},{title:"Views",value:w},{title:"Comments",value:B},{title:"Downloads",value:I}].map(({title:M,value:C})=>`
        <div class="info-block">
          <span class="info-title">${M}</span>
          <span class="info-value">${C}</span>
        </div>
      `).join(""),c=document.createElement("li");c.classList.add("gallery-item"),c.innerHTML=`
      <a href="${o}" class="gallery-link">
        <div class="image-wrapper">
          <img
            src="${e}"
            alt="${s}"
            class="gallery-image hidden"
          />
        </div>
      </a>
      <div class="gallery-info">
        ${L}
      </div>
    `;const m=c.querySelector(".gallery-image");m.onload=()=>{m.classList.remove("hidden")},l.appendChild(c),setTimeout(()=>{c.classList.add("fade-in")},b*100)}),g?g.refresh():g=new S(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),l.children.length>0){const o=l.children[0].getBoundingClientRect(),s=window.getComputedStyle(l),i=parseInt(s.gap)||24;return o.height+i}return 0}const r={form:document.getElementById("searchForm"),inputField:document.getElementById("searchInput"),gallery:document.getElementById("gallery"),loadMoreBtn:document.getElementById("loadMoreBtn"),loader:document.getElementById("loader")};let d=1,u="",y=0;r.form.addEventListener("submit",async n=>{if(n.preventDefault(),u=r.inputField.value.trim(),!!u){d=1,r.gallery.innerHTML="",r.loadMoreBtn.style.display="none",r.loader.style.display="flex";try{const t=await v(u,d);if(y=t.totalHits,E(t),r.gallery.children.length>0){const a=document.querySelector("header"),l=a?a.offsetHeight:0,e=r.gallery.getBoundingClientRect().top+window.scrollY;window.scrollTo({top:e-l-20,behavior:"smooth"})}y>15?r.loadMoreBtn.style.display="block":t.hits.length>0&&t.hits.length===y&&p("We're sorry, but you've reached the end of search results.")}catch(t){console.error("Error:",t)}finally{r.loader.style.display="none",r.inputField.blur()}}});r.loadMoreBtn.addEventListener("click",async()=>{d+=1,r.loadMoreBtn.style.display="none",r.loader.style.display="flex";try{const n=await v(u,d),t=E(n,!0);if(t){const l=r.gallery.clientWidth,e=358,o=24,s=Math.floor((l+o)/(e+o)),i=Math.ceil(n.hits.length/s);window.scrollBy({top:t*i,behavior:"smooth"})}d*15>=y?(r.loadMoreBtn.style.display="none",p("We're sorry, but you've reached the end of search results.")):r.loadMoreBtn.style.display="block"}catch(n){console.error("Error:",n)}finally{r.loader.style.display="none"}});
//# sourceMappingURL=index.js.map
